from __future__ import annotations

from typing import Optional

import yfinance as yf

# Mapeo estatico ticker -> sector GICS (uno de los 11 sectores estandar).
# Estatico (no se consulta por red) a proposito: RulesEngine.evaluate() es
# sincrono y sin llamadas de red por diseno (ver rules.py), y el limite de
# concentracion por sector necesita resolver el sector de una orden dentro de
# ese mismo camino caliente. Un dict en memoria resuelve eso con un lookup
# instantaneo en vez de forzar un fetch bloqueante (o un refactor async de
# evaluate() y de todos sus llamadores) solo para esta feature.
#
# Cada entrada fue verificada contra al menos una fuente financiera real
# (mismo estandar que GROWTH_TICKERS en screener_config.py, via un agente de
# investigacion dedicado). Cualquier ticker no presente devuelve None en
# get_sector(), y todo el codigo que la consume (RulesEngine, SignalResult.sector)
# trata None como "sin dato, no bloquea" en vez de fallar.
TICKER_SECTOR: dict[str, str] = {
    "A": "Health Care",
    "AAPL": "Information Technology",
    "ABAT": "Industrials",
    "ABBV": "Health Care",
    "ABNB": "Consumer Discretionary",
    "ABT": "Health Care",
    "ACGL": "Financials",
    "ACHR": "Industrials",
    "ACMR": "Information Technology",
    "ACN": "Information Technology",
    "ADBE": "Information Technology",
    "ADI": "Information Technology",
    "ADM": "Consumer Staples",
    "ADMA": "Health Care",
    "ADP": "Industrials",
    "ADSK": "Information Technology",
    "AEE": "Utilities",
    "AEHR": "Information Technology",
    "AEP": "Utilities",
    "AES": "Utilities",
    "AFL": "Financials",
    "AIG": "Financials",
    "AIZ": "Financials",
    "AJG": "Financials",
    "AKAM": "Information Technology",
    "ALB": "Materials",
    "ALGN": "Health Care",
    "ALL": "Financials",
    "ALLE": "Industrials",
    "ALRM": "Information Technology",
    "AMAT": "Information Technology",
    "AMBA": "Information Technology",
    "AMCR": "Materials",
    "AMD": "Information Technology",
    "AME": "Industrials",
    "AMGN": "Health Care",
    "AMP": "Financials",
    "AMPX": "Industrials",
    "AMRC": "Industrials",
    "AMT": "Real Estate",
    "AMZN": "Consumer Discretionary",
    "ANET": "Information Technology",
    "AON": "Financials",
    "AOS": "Industrials",
    "AOSL": "Information Technology",
    "APA": "Energy",
    "APD": "Materials",
    "APH": "Information Technology",
    "APO": "Financials",
    "APP": "Information Technology",
    "APTV": "Consumer Discretionary",
    "ARE": "Real Estate",
    "ARES": "Financials",
    "ASYS": "Information Technology",
    "ATLX": "Materials",
    "ATO": "Utilities",
    "AVAV": "Industrials",
    "AVB": "Real Estate",
    "AVGO": "Information Technology",
    "AVY": "Materials",
    "AWK": "Utilities",
    "AXON": "Industrials",
    "AXP": "Financials",
    "AZO": "Consumer Discretionary",
    "BA": "Industrials",
    "BAC": "Financials",
    "BALL": "Materials",
    "BAX": "Health Care",
    "BB": "Information Technology",
    "BBY": "Consumer Discretionary",
    "BDX": "Health Care",
    "BEN": "Financials",
    "BF-B": "Consumer Staples",
    "BG": "Consumer Staples",
    "BIIB": "Health Care",
    "BKNG": "Consumer Discretionary",
    "BKR": "Energy",
    "BKSY": "Industrials",
    "BLDR": "Industrials",
    "BLK": "Financials",
    "BMY": "Health Care",
    "BNY": "Financials",
    "BR": "Industrials",
    "BRK-B": "Financials",
    "BRO": "Financials",
    "BSX": "Health Care",
    "BX": "Financials",
    "BXP": "Real Estate",
    "C": "Financials",
    "CAG": "Consumer Staples",
    "CAH": "Health Care",
    "CAMT": "Information Technology",
    "CARR": "Industrials",
    "CASY": "Consumer Staples",
    "CAT": "Industrials",
    "CB": "Financials",
    "CBOE": "Financials",
    "CBRE": "Real Estate",
    "CCI": "Real Estate",
    "CCL": "Consumer Discretionary",
    "CDNS": "Information Technology",
    "CDW": "Information Technology",
    "CEG": "Utilities",
    "CEVA": "Information Technology",
    "CF": "Materials",
    "CFG": "Financials",
    "CHD": "Consumer Staples",
    "CHRW": "Industrials",
    "CHTR": "Communication Services",
    "CHYM": "Financials",
    "CI": "Health Care",
    "CIEN": "Information Technology",
    "CINF": "Financials",
    "CL": "Consumer Staples",
    "CLX": "Consumer Staples",
    "CMCSA": "Communication Services",
    "CME": "Financials",
    "CMG": "Consumer Discretionary",
    "CMI": "Industrials",
    "CMS": "Utilities",
    "CNC": "Health Care",
    "CNP": "Utilities",
    "COF": "Financials",
    "COHR": "Information Technology",
    "COHU": "Information Technology",
    "COIN": "Financials",
    "COO": "Health Care",
    "COP": "Energy",
    "COR": "Health Care",
    "COST": "Consumer Staples",
    "CPAY": "Financials",
    "CPB": "Consumer Staples",
    "CPRT": "Industrials",
    "CPT": "Real Estate",
    "CRBU": "Health Care",
    "CRCL": "Financials",
    "CRH": "Materials",
    "CRL": "Health Care",
    "CRM": "Information Technology",
    "CRML": "Materials",
    "CRNX": "Health Care",
    "CRWD": "Information Technology",
    "CRWV": "Information Technology",
    "CSCO": "Information Technology",
    "CSGP": "Real Estate",
    "CSX": "Industrials",
    "CTAS": "Industrials",
    "CTSH": "Information Technology",
    "CTVA": "Materials",
    "CURO": "Financials",
    "CVNA": "Consumer Discretionary",
    "CVS": "Health Care",
    "CVX": "Energy",
    "D": "Utilities",
    "DAL": "Industrials",
    "DASH": "Consumer Discretionary",
    "DD": "Materials",
    "DDOG": "Information Technology",
    "DE": "Industrials",
    "DECK": "Consumer Discretionary",
    "DELL": "Information Technology",
    "DG": "Consumer Staples",
    "DGX": "Health Care",
    "DHI": "Consumer Discretionary",
    "DHR": "Health Care",
    "DIS": "Communication Services",
    "DLR": "Real Estate",
    "DLTR": "Consumer Staples",
    "DOC": "Real Estate",
    "DOV": "Industrials",
    "DOW": "Materials",
    "DPZ": "Consumer Discretionary",
    "DRI": "Consumer Discretionary",
    "DTE": "Utilities",
    "DUK": "Utilities",
    "DVA": "Health Care",
    "DVN": "Energy",
    "DXCM": "Health Care",
    "EA": "Communication Services",
    "EBAY": "Consumer Discretionary",
    "ECL": "Materials",
    "ED": "Utilities",
    "EFX": "Industrials",
    "EG": "Financials",
    "EIX": "Utilities",
    "EL": "Consumer Staples",
    "ELV": "Health Care",
    "ELVA": "Industrials",
    "EME": "Industrials",
    "EMR": "Industrials",
    "EOG": "Energy",
    "EOSE": "Industrials",
    "EQIX": "Real Estate",
    "EQR": "Real Estate",
    "EQT": "Energy",
    "ERIE": "Financials",
    "ES": "Utilities",
    "ESS": "Real Estate",
    "ETN": "Industrials",
    "ETR": "Utilities",
    "EVRG": "Utilities",
    "EW": "Health Care",
    "EXC": "Utilities",
    "EXE": "Energy",
    "EXPD": "Industrials",
    "EXPE": "Consumer Discretionary",
    "EXR": "Real Estate",
    "F": "Consumer Discretionary",
    "FANG": "Energy",
    "FAST": "Industrials",
    "FCX": "Materials",
    "FDS": "Financials",
    "FDX": "Industrials",
    "FDXF": "Industrials",
    "FE": "Utilities",
    "FFIV": "Information Technology",
    "FICO": "Information Technology",
    "FIS": "Financials",
    "FISV": "Financials",
    "FITB": "Financials",
    "FIVN": "Information Technology",
    "FIX": "Industrials",
    "FLNC": "Industrials",
    "FOX": "Communication Services",
    "FOXA": "Communication Services",
    "FRT": "Real Estate",
    "FSLR": "Information Technology",
    "FTNT": "Information Technology",
    "FTV": "Industrials",
    "GD": "Industrials",
    "GDDY": "Information Technology",
    "GDOT": "Financials",
    "GE": "Industrials",
    "GEHC": "Health Care",
    "GEN": "Information Technology",
    "GEV": "Industrials",
    "GILD": "Health Care",
    "GIS": "Consumer Staples",
    "GL": "Financials",
    "GLW": "Information Technology",
    "GM": "Consumer Discretionary",
    "GNRC": "Industrials",
    "GOOG": "Communication Services",
    "GOOGL": "Communication Services",
    "GPC": "Consumer Discretionary",
    "GPN": "Financials",
    "GRC": "Industrials",
    "GRMN": "Consumer Discretionary",
    "GS": "Financials",
    "GWH": "Industrials",
    "GWW": "Industrials",
    "HAL": "Energy",
    "HAS": "Consumer Discretionary",
    "HBAN": "Financials",
    "HCA": "Health Care",
    "HD": "Consumer Discretionary",
    "HIG": "Financials",
    "HII": "Industrials",
    "HLT": "Consumer Discretionary",
    "HON": "Industrials",
    "HOOD": "Financials",
    "HPE": "Information Technology",
    "HPQ": "Information Technology",
    "HRL": "Consumer Staples",
    "HSIC": "Health Care",
    "HST": "Real Estate",
    "HSY": "Consumer Staples",
    "HUBB": "Industrials",
    "HUM": "Health Care",
    "HWM": "Industrials",
    "IBKR": "Financials",
    "IBM": "Information Technology",
    "ICE": "Financials",
    "ICHR": "Information Technology",
    "IDXX": "Health Care",
    "IEX": "Industrials",
    "IFF": "Materials",
    "INCY": "Health Care",
    "INO": "Health Care",
    "INOD": "Information Technology",
    "INTC": "Information Technology",
    "INTU": "Information Technology",
    "INVH": "Real Estate",
    "IONQ": "Information Technology",
    "IP": "Materials",
    "IQV": "Health Care",
    "IR": "Industrials",
    "IRM": "Real Estate",
    "ISRG": "Health Care",
    "IT": "Information Technology",
    "ITW": "Industrials",
    "IVZ": "Financials",
    "J": "Industrials",
    "JBHT": "Industrials",
    "JBL": "Information Technology",
    "JCI": "Industrials",
    "JKHY": "Financials",
    "JNJ": "Health Care",
    "JOBY": "Industrials",
    "JPM": "Financials",
    "KDP": "Consumer Staples",
    "KEY": "Financials",
    "KEYS": "Information Technology",
    "KHC": "Consumer Staples",
    "KIM": "Real Estate",
    "KKR": "Financials",
    "KLAC": "Information Technology",
    "KLIC": "Information Technology",
    "KMB": "Consumer Staples",
    "KMI": "Energy",
    "KO": "Consumer Staples",
    "KR": "Consumer Staples",
    "KRMD": "Health Care",
    "KTOS": "Industrials",
    "KVUE": "Consumer Staples",
    "L": "Financials",
    "LC": "Financials",
    "LDOS": "Industrials",
    "LEN": "Consumer Discretionary",
    "LH": "Health Care",
    "LHX": "Industrials",
    "LII": "Industrials",
    "LIN": "Materials",
    "LITE": "Information Technology",
    "LLY": "Health Care",
    "LMT": "Industrials",
    "LNT": "Utilities",
    "LOW": "Consumer Discretionary",
    "LRCX": "Information Technology",
    "LULU": "Consumer Discretionary",
    "LUNR": "Industrials",
    "LUV": "Industrials",
    "LVS": "Consumer Discretionary",
    "LYB": "Materials",
    "LYV": "Communication Services",
    "MA": "Financials",
    "MAA": "Real Estate",
    "MAMA": "Consumer Staples",
    "MAR": "Consumer Discretionary",
    "MAS": "Industrials",
    "MCD": "Consumer Discretionary",
    "MCHP": "Information Technology",
    "MCK": "Health Care",
    "MCO": "Financials",
    "MDLZ": "Consumer Staples",
    "MDT": "Health Care",
    "MDXH": "Health Care",
    "MET": "Financials",
    "META": "Communication Services",
    "MGM": "Consumer Discretionary",
    "MKC": "Consumer Staples",
    "MLM": "Materials",
    "MMM": "Industrials",
    "MNST": "Consumer Staples",
    "MO": "Consumer Staples",
    "MOS": "Materials",
    "MP": "Materials",
    "MPC": "Energy",
    "MPWR": "Information Technology",
    "MRK": "Health Care",
    "MRNA": "Health Care",
    "MRSH": "Financials",
    "MS": "Financials",
    "MSCI": "Financials",
    "MSFT": "Information Technology",
    "MSI": "Information Technology",
    "MTB": "Financials",
    "MTD": "Health Care",
    "MU": "Information Technology",
    "MUX": "Materials",
    "MWA": "Industrials",
    "NAK": "Materials",
    "NCLH": "Consumer Discretionary",
    "NDAQ": "Financials",
    "NDSN": "Industrials",
    "NEE": "Utilities",
    "NEM": "Materials",
    "NFLX": "Communication Services",
    "NG": "Materials",
    "NI": "Utilities",
    "NKE": "Consumer Discretionary",
    "NOC": "Industrials",
    "NOW": "Information Technology",
    "NRG": "Utilities",
    "NSC": "Industrials",
    "NTAP": "Information Technology",
    "NTRS": "Financials",
    "NUE": "Materials",
    "NVDA": "Information Technology",
    "NVR": "Consumer Discretionary",
    "NWS": "Communication Services",
    "NWSA": "Communication Services",
    "NXPI": "Information Technology",
    "O": "Real Estate",
    "ODFL": "Industrials",
    "OKE": "Energy",
    "OKLO": "Utilities",
    "OMC": "Communication Services",
    "OMCL": "Health Care",
    "ON": "Information Technology",
    "ONDS": "Information Technology",
    "ORCL": "Information Technology",
    "ORLY": "Consumer Discretionary",
    "OTIS": "Industrials",
    "OTLY": "Consumer Staples",
    "OUST": "Information Technology",
    "OXY": "Energy",
    "PANW": "Information Technology",
    "PATH": "Information Technology",
    "PAYX": "Industrials",
    "PCAR": "Industrials",
    "PCG": "Utilities",
    "PEG": "Utilities",
    "PEP": "Consumer Staples",
    "PFE": "Health Care",
    "PFG": "Financials",
    "PG": "Consumer Staples",
    "PGR": "Financials",
    "PH": "Industrials",
    "PHM": "Consumer Discretionary",
    "PKG": "Materials",
    "PLD": "Real Estate",
    "PLTR": "Information Technology",
    "PM": "Consumer Staples",
    "PNC": "Financials",
    "PNR": "Industrials",
    "PNW": "Utilities",
    "PODD": "Health Care",
    "POOL": "Consumer Discretionary",
    "PPG": "Materials",
    "PPL": "Utilities",
    "PRU": "Financials",
    "PSA": "Real Estate",
    "PSKY": "Communication Services",
    "PSX": "Energy",
    "PTC": "Information Technology",
    "PVLA": "Health Care",
    "PWR": "Industrials",
    "PYPL": "Financials",
    "Q": "Information Technology",
    "QBTS": "Information Technology",
    "QCOM": "Information Technology",
    "QFIN": "Financials",
    "QLYS": "Information Technology",
    "QS": "Industrials",
    "QUBT": "Information Technology",
    "RCL": "Consumer Discretionary",
    "RDW": "Industrials",
    "RDWR": "Information Technology",
    "REG": "Real Estate",
    "REGN": "Health Care",
    "RF": "Financials",
    "RGTI": "Information Technology",
    "RJF": "Financials",
    "RKLB": "Industrials",
    "RL": "Consumer Discretionary",
    "RMD": "Health Care",
    "ROK": "Industrials",
    "ROL": "Industrials",
    "ROP": "Information Technology",
    "ROST": "Consumer Discretionary",
    "RPAY": "Financials",
    "RR": "Industrials",
    "RSG": "Industrials",
    "RTX": "Industrials",
    "RUN": "Utilities",
    "RVTY": "Health Care",
    "S": "Information Technology",
    "SATS": "Communication Services",
    "SBAC": "Real Estate",
    "SBUX": "Consumer Discretionary",
    "SCHW": "Financials",
    "SCWX": "Information Technology",
    "SERV": "Industrials",
    "SEZL": "Financials",
    "SGMO": "Health Care",
    "SHW": "Materials",
    "SIDU": "Industrials",
    "SJM": "Consumer Staples",
    "SLB": "Energy",
    "SLDP": "Industrials",
    "SMCI": "Information Technology",
    "SNA": "Industrials",
    "SNDK": "Information Technology",
    "SNPS": "Information Technology",
    "SO": "Utilities",
    "SOFI": "Financials",
    "SOLV": "Health Care",
    "SOUN": "Information Technology",
    "SPG": "Real Estate",
    "SPGI": "Financials",
    "SRE": "Utilities",
    "STE": "Health Care",
    "STEM": "Industrials",
    "STLD": "Materials",
    "STT": "Financials",
    "STX": "Information Technology",
    "STZ": "Consumer Staples",
    "SW": "Materials",
    "SWK": "Industrials",
    "SWKS": "Information Technology",
    "SYF": "Financials",
    "SYK": "Health Care",
    "SYY": "Consumer Staples",
    "T": "Communication Services",
    "TAP": "Consumer Staples",
    "TDC": "Information Technology",
    "TDG": "Industrials",
    "TDY": "Information Technology",
    "TECH": "Health Care",
    "TEL": "Information Technology",
    "TER": "Information Technology",
    "TERN": "Health Care",
    "TFC": "Financials",
    "TGT": "Consumer Staples",
    "TJX": "Consumer Discretionary",
    "TKO": "Communication Services",
    "TMC": "Materials",
    "TMO": "Health Care",
    "TMUS": "Communication Services",
    "TPL": "Energy",
    "TPR": "Consumer Discretionary",
    "TRGP": "Energy",
    "TRMB": "Information Technology",
    "TROW": "Financials",
    "TRV": "Financials",
    "TSCO": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",
    "TSN": "Consumer Staples",
    "TT": "Industrials",
    "TTD": "Communication Services",
    "TTWO": "Communication Services",
    "TXN": "Information Technology",
    "TXT": "Industrials",
    "TYL": "Information Technology",
    "UAL": "Industrials",
    "UBER": "Industrials",
    "UDR": "Real Estate",
    "UHS": "Health Care",
    "ULTA": "Consumer Discretionary",
    "UNH": "Health Care",
    "UNP": "Industrials",
    "UPS": "Industrials",
    "URI": "Industrials",
    "USAR": "Materials",
    "USB": "Financials",
    "V": "Financials",
    "VEEV": "Health Care",
    "VICI": "Real Estate",
    "VKTX": "Health Care",
    "VLO": "Energy",
    "VLTO": "Industrials",
    "VMC": "Materials",
    "VRNS": "Information Technology",
    "VRSK": "Industrials",
    "VRSN": "Information Technology",
    "VRT": "Industrials",
    "VRTX": "Health Care",
    "VST": "Utilities",
    "VTR": "Real Estate",
    "VTRS": "Health Care",
    "VZ": "Communication Services",
    "WAB": "Industrials",
    "WAT": "Health Care",
    "WBD": "Communication Services",
    "WDAY": "Information Technology",
    "WDC": "Information Technology",
    "WEC": "Utilities",
    "WELL": "Real Estate",
    "WFC": "Financials",
    "WM": "Industrials",
    "WMB": "Energy",
    "WMT": "Consumer Staples",
    "WRB": "Financials",
    "WSM": "Consumer Discretionary",
    "WST": "Health Care",
    "WTTR": "Energy",
    "WTW": "Financials",
    "WY": "Real Estate",
    "WYNN": "Consumer Discretionary",
    "XEL": "Utilities",
    "XOM": "Energy",
    "XYL": "Industrials",
    "XYZ": "Financials",
    "YUM": "Consumer Discretionary",
    "ZBH": "Health Care",
    "ZBRA": "Information Technology",
    "ZS": "Information Technology",
    "ZTS": "Health Care",
}

_VALID_SECTORS = frozenset({
    "Information Technology",
    "Health Care",
    "Financials",
    "Consumer Discretionary",
    "Consumer Staples",
    "Communication Services",
    "Industrials",
    "Energy",
    "Utilities",
    "Real Estate",
    "Materials",
})

# ETF sectorial SPDR de cada sector GICS: permite medir la fuerza relativa de
# un simbolo contra su propio sector (en vez de solo contra el benchmark
# general, ej. SPY), reusando get_daily_bars (ya cacheado) en lugar de pedir
# una canasta de pares por simbolo.
SECTOR_ETF: dict[str, str] = {
    "Information Technology": "XLK",
    "Health Care": "XLV",
    "Financials": "XLF",
    "Consumer Discretionary": "XLY",
    "Consumer Staples": "XLP",
    "Communication Services": "XLC",
    "Industrials": "XLI",
    "Energy": "XLE",
    "Utilities": "XLU",
    "Real Estate": "XLRE",
    "Materials": "XLB",
}


def get_sector(symbol: str) -> Optional[str]:
    """Sector GICS de `symbol`, o None si no esta clasificado todavia.

    No golpea la red: ademas del mapeo estatico (curado a mano), consulta
    `_runtime_sector_cache`, poblado unicamente por `refresh_sector()`/el
    endpoint "refrescar sectores" del dashboard. Esto preserva la garantia de
    RulesEngine.evaluate() (sincrono, sin red) sin perder la clasificacion de
    un ticker nuevo una vez que alguien la pidio explicitamente."""
    key = symbol.upper()
    sector = TICKER_SECTOR.get(key)
    if sector is not None:
        return sector
    return _runtime_sector_cache.get(key)


# Yahoo Finance (yfinance .info["sector"]) usa su propia taxonomia (Morningstar),
# distinta en nombres de los 11 sectores GICS estandar que usa el resto del
# codigo (_VALID_SECTORS). Se traduce aca para que un ticker resuelto en vivo
# sea indistinguible, para RulesEngine y el frontend, de uno del mapeo estatico.
_YFINANCE_SECTOR_MAP: dict[str, str] = {
    "Technology": "Information Technology",
    "Healthcare": "Health Care",
    "Financial Services": "Financials",
    "Consumer Cyclical": "Consumer Discretionary",
    "Consumer Defensive": "Consumer Staples",
    "Industrials": "Industrials",
    "Energy": "Energy",
    "Utilities": "Utilities",
    "Real Estate": "Real Estate",
    "Basic Materials": "Materials",
    "Communication Services": "Communication Services",
}

# Cache de tickers resueltos en vivo (ver refresh_sector). Separado de
# TICKER_SECTOR (el mapeo curado a mano) para no mezclar datos verificados con
# datos de mejor esfuerzo provenientes de una API de terceros sin garantias.
_runtime_sector_cache: dict[str, Optional[str]] = {}


def refresh_sector(symbol: str) -> Optional[str]:
    """Resuelve el sector de `symbol` contra Yahoo Finance y lo cachea en
    `_runtime_sector_cache` para que `get_sector()` lo siga devolviendo sin
    red. Pensado para tickers nuevos que el usuario agrega al universo desde
    el dashboard y que todavia no estan en el mapeo estatico TICKER_SECTOR.

    Llamada explicita y fuera del camino caliente de RulesEngine (ver
    docstring de get_sector): quien la invoca (el endpoint
    POST /api/sectors/refresh) es responsable de no llamarla desde codigo
    sincrono que deba permanecer libre de red."""
    key = symbol.upper()
    try:
        info = yf.Ticker(symbol).get_info() or {}
    except Exception:
        info = {}
    raw_sector = info.get("sector")
    sector = _YFINANCE_SECTOR_MAP.get(raw_sector) if raw_sector else None
    _runtime_sector_cache[key] = sector
    return sector
