from __future__ import annotations

from typing import Optional

import yfinance as yf

from .market_data import _fetch_with_timeout

# Mapeo estatico ticker -> sector GICS (uno de los 11 sectores estandar).
# Estatico (no se consulta por red) a proposito: RulesEngine.evaluate() es
# sincrono y sin llamadas de red por diseno (ver rules.py), y el limite de
# concentracion por sector necesita resolver el sector de una orden dentro de
# ese mismo camino caliente. Un dict en memoria resuelve eso con un lookup
# instantaneo en vez de forzar un fetch bloqueante (o un refactor async de
# evaluate() y de todos sus llamadores) solo para esta feature.
#
# Cada entrada fue verificada contra al menos una fuente financiera real
# (mismo estandar que GROWTH_TICKERS en screener_config.py, via un agente de
# investigacion dedicado). Cualquier ticker no presente devuelve None en
# get_sector(), y todo el codigo que la consume (RulesEngine, SignalResult.sector)
# trata None como "sin dato, no bloquea" en vez de fallar.
TICKER_SECTOR: dict[str, str] = {
    "A": "Health Care",
    "AAPL": "Information Technology",
    "ABAT": "Industrials",
    "ABBV": "Health Care",
    "ABNB": "Consumer Discretionary",
    "ABT": "Health Care",
    "ACGL": "Financials",
    "ACHR": "Industrials",
    "ACMR": "Information Technology",
    "ACN": "Information Technology",
    "ADBE": "Information Technology",
    "ADI": "Information Technology",
    "ADM": "Consumer Staples",
    "ADMA": "Health Care",
    "ADP": "Industrials",
    "ADSK": "Information Technology",
    "AEE": "Utilities",
    "AEHR": "Information Technology",
    "AEP": "Utilities",
    "AES": "Utilities",
    "AFL": "Financials",
    "AIG": "Financials",
    "AIZ": "Financials",
    "AJG": "Financials",
    "AKAM": "Information Technology",
    "ALB": "Materials",
    "ALGN": "Health Care",
    "ALL": "Financials",
    "ALLE": "Industrials",
    "ALRM": "Information Technology",
    "AMAT": "Information Technology",
    "AMBA": "Information Technology",
    "AMCR": "Materials",
    "AMD": "Information Technology",
    "AME": "Industrials",
    "AMGN": "Health Care",
    "AMP": "Financials",
    "AMPX": "Industrials",
    "AMRC": "Industrials",
    "AMT": "Real Estate",
    "AMZN": "Consumer Discretionary",
    "ANET": "Information Technology",
    "AON": "Financials",
    "AOS": "Industrials",
    "AOSL": "Information Technology",
    "APA": "Energy",
    "APD": "Materials",
    "APH": "Information Technology",
    "APO": "Financials",
    "APP": "Information Technology",
    "APTV": "Consumer Discretionary",
    "ARE": "Real Estate",
    "ARES": "Financials",
    "ASYS": "Information Technology",
    "ATLX": "Materials",
    "ATO": "Utilities",
    "AVAV": "Industrials",
    "AVB": "Real Estate",
    "AVGO": "Information Technology",
    "AVY": "Materials",
    "AWK": "Utilities",
    "AXON": "Industrials",
    "AXP": "Financials",
    "AZO": "Consumer Discretionary",
    "BA": "Industrials",
    "BAC": "Financials",
    "BALL": "Materials",
    "BAX": "Health Care",
    "BB": "Information Technology",
    "BBY": "Consumer Discretionary",
    "BDX": "Health Care",
    "BEN": "Financials",
    "BF-B": "Consumer Staples",
    "BG": "Consumer Staples",
    "BIIB": "Health Care",
    "BKNG": "Consumer Discretionary",
    "BKR": "Energy",
    "BKSY": "Industrials",
    "BLDR": "Industrials",
    "BLK": "Financials",
    "BMY": "Health Care",
    "BNY": "Financials",
    "BR": "Industrials",
    "BRK-B": "Financials",
    "BRO": "Financials",
    "BSX": "Health Care",
    "BX": "Financials",
    "BXP": "Real Estate",
    "C": "Financials",
    "CAG": "Consumer Staples",
    "CAH": "Health Care",
    "CAMT": "Information Technology",
    "CARR": "Industrials",
    "CASY": "Consumer Staples",
    "CAT": "Industrials",
    "CB": "Financials",
    "CBOE": "Financials",
    "CBRE": "Real Estate",
    "CCI": "Real Estate",
    "CCL": "Consumer Discretionary",
    "CDNS": "Information Technology",
    "CDW": "Information Technology",
    "CEG": "Utilities",
    "CEVA": "Information Technology",
    "CF": "Materials",
    "CFG": "Financials",
    "CHD": "Consumer Staples",
    "CHRW": "Industrials",
    "CHTR": "Communication Services",
    "CHYM": "Financials",
    "CI": "Health Care",
    "CIEN": "Information Technology",
    "CINF": "Financials",
    "CL": "Consumer Staples",
    "CLX": "Consumer Staples",
    "CMCSA": "Communication Services",
    "CME": "Financials",
    "CMG": "Consumer Discretionary",
    "CMI": "Industrials",
    "CMS": "Utilities",
    "CNC": "Health Care",
    "CNP": "Utilities",
    "COF": "Financials",
    "COHR": "Information Technology",
    "COHU": "Information Technology",
    "COIN": "Financials",
    "COO": "Health Care",
    "COP": "Energy",
    "COR": "Health Care",
    "COST": "Consumer Staples",
    "CPAY": "Financials",
    "CPB": "Consumer Staples",
    "CPRT": "Industrials",
    "CPT": "Real Estate",
    "CRBU": "Health Care",
    "CRCL": "Financials",
    "CRH": "Materials",
    "CRL": "Health Care",
    "CRM": "Information Technology",
    "CRML": "Materials",
    "CRNX": "Health Care",
    "CRWD": "Information Technology",
    "CRWV": "Information Technology",
    "CSCO": "Information Technology",
    "CSGP": "Real Estate",
    "CSX": "Industrials",
    "CTAS": "Industrials",
    "CTSH": "Information Technology",
    "CTVA": "Materials",
    "CURO": "Financials",
    "CVNA": "Consumer Discretionary",
    "CVS": "Health Care",
    "CVX": "Energy",
    "D": "Utilities",
    "DAL": "Industrials",
    "DASH": "Consumer Discretionary",
    "DD": "Materials",
    "DDOG": "Information Technology",
    "DE": "Industrials",
    "DECK": "Consumer Discretionary",
    "DELL": "Information Technology",
    "DG": "Consumer Staples",
    "DGX": "Health Care",
    "DHI": "Consumer Discretionary",
    "DHR": "Health Care",
    "DIS": "Communication Services",
    "DLR": "Real Estate",
    "DLTR": "Consumer Staples",
    "DOC": "Real Estate",
    "DOV": "Industrials",
    "DOW": "Materials",
    "DPZ": "Consumer Discretionary",
    "DRI": "Consumer Discretionary",
    "DTE": "Utilities",
    "DUK": "Utilities",
    "DVA": "Health Care",
    "DVN": "Energy",
    "DXCM": "Health Care",
    "EA": "Communication Services",
    "EBAY": "Consumer Discretionary",
    "ECL": "Materials",
    "ED": "Utilities",
    "EFX": "Industrials",
    "EG": "Financials",
    "EIX": "Utilities",
    "EL": "Consumer Staples",
    "ELV": "Health Care",
    "ELVA": "Industrials",
    "EME": "Industrials",
    "EMR": "Industrials",
    "EOG": "Energy",
    "EOSE": "Industrials",
    "EQIX": "Real Estate",
    "EQR": "Real Estate",
    "EQT": "Energy",
    "ERIE": "Financials",
    "ES": "Utilities",
    "ESS": "Real Estate",
    "ETN": "Industrials",
    "ETR": "Utilities",
    "EVRG": "Utilities",
    "EW": "Health Care",
    "EXC": "Utilities",
    "EXE": "Energy",
    "EXPD": "Industrials",
    "EXPE": "Consumer Discretionary",
    "EXR": "Real Estate",
    "F": "Consumer Discretionary",
    "FANG": "Energy",
    "FAST": "Industrials",
    "FCX": "Materials",
    "FDS": "Financials",
    "FDX": "Industrials",
    "FDXF": "Industrials",
    "FE": "Utilities",
    "FFIV": "Information Technology",
    "FICO": "Information Technology",
    "FIS": "Financials",
    "FISV": "Financials",
    "FITB": "Financials",
    "FIVN": "Information Technology",
    "FIX": "Industrials",
    "FLNC": "Industrials",
    "FOX": "Communication Services",
    "FOXA": "Communication Services",
    "FRT": "Real Estate",
    "FSLR": "Information Technology",
    "FTNT": "Information Technology",
    "FTV": "Industrials",
    "GD": "Industrials",
    "GDDY": "Information Technology",
    "GDOT": "Financials",
    "GE": "Industrials",
    "GEHC": "Health Care",
    "GEN": "Information Technology",
    "GEV": "Industrials",
    "GILD": "Health Care",
    "GIS": "Consumer Staples",
    "GL": "Financials",
    "GLW": "Information Technology",
    "GM": "Consumer Discretionary",
    "GNRC": "Industrials",
    "GOOG": "Communication Services",
    "GOOGL": "Communication Services",
    "GPC": "Consumer Discretionary",
    "GPN": "Financials",
    "GRC": "Industrials",
    "GRMN": "Consumer Discretionary",
    "GS": "Financials",
    "GWH": "Industrials",
    "GWW": "Industrials",
    "HAL": "Energy",
    "HAS": "Consumer Discretionary",
    "HBAN": "Financials",
    "HCA": "Health Care",
    "HD": "Consumer Discretionary",
    "HIG": "Financials",
    "HII": "Industrials",
    "HLT": "Consumer Discretionary",
    "HON": "Industrials",
    "HOOD": "Financials",
    "HPE": "Information Technology",
    "HPQ": "Information Technology",
    "HRL": "Consumer Staples",
    "HSIC": "Health Care",
    "HST": "Real Estate",
    "HSY": "Consumer Staples",
    "HUBB": "Industrials",
    "HUM": "Health Care",
    "HWM": "Industrials",
    "IBKR": "Financials",
    "IBM": "Information Technology",
    "ICE": "Financials",
    "ICHR": "Information Technology",
    "IDXX": "Health Care",
    "IEX": "Industrials",
    "IFF": "Materials",
    "INCY": "Health Care",
    "INO": "Health Care",
    "INOD": "Information Technology",
    "INTC": "Information Technology",
    "INTU": "Information Technology",
    "INVH": "Real Estate",
    "IONQ": "Information Technology",
    "IP": "Materials",
    "IQV": "Health Care",
    "IR": "Industrials",
    "IRM": "Real Estate",
    "ISRG": "Health Care",
    "IT": "Information Technology",
    "ITW": "Industrials",
    "IVZ": "Financials",
    "J": "Industrials",
    "JBHT": "Industrials",
    "JBL": "Information Technology",
    "JCI": "Industrials",
    "JKHY": "Financials",
    "JNJ": "Health Care",
    "JOBY": "Industrials",
    "JPM": "Financials",
    "KDP": "Consumer Staples",
    "KEY": "Financials",
    "KEYS": "Information Technology",
    "KHC": "Consumer Staples",
    "KIM": "Real Estate",
    "KKR": "Financials",
    "KLAC": "Information Technology",
    "KLIC": "Information Technology",
    "KMB": "Consumer Staples",
    "KMI": "Energy",
    "KO": "Consumer Staples",
    "KR": "Consumer Staples",
    "KRMD": "Health Care",
    "KTOS": "Industrials",
    "KVUE": "Consumer Staples",
    "L": "Financials",
    "LC": "Financials",
    "LDOS": "Industrials",
    "LEN": "Consumer Discretionary",
    "LH": "Health Care",
    "LHX": "Industrials",
    "LII": "Industrials",
    "LIN": "Materials",
    "LITE": "Information Technology",
    "LLY": "Health Care",
    "LMT": "Industrials",
    "LNT": "Utilities",
    "LOW": "Consumer Discretionary",
    "LRCX": "Information Technology",
    "LULU": "Consumer Discretionary",
    "LUNR": "Industrials",
    "LUV": "Industrials",
    "LVS": "Consumer Discretionary",
    "LYB": "Materials",
    "LYV": "Communication Services",
    "MA": "Financials",
    "MAA": "Real Estate",
    "MAMA": "Consumer Staples",
    "MAR": "Consumer Discretionary",
    "MAS": "Industrials",
    "MCD": "Consumer Discretionary",
    "MCHP": "Information Technology",
    "MCK": "Health Care",
    "MCO": "Financials",
    "MDLZ": "Consumer Staples",
    "MDT": "Health Care",
    "MDXH": "Health Care",
    "MET": "Financials",
    "META": "Communication Services",
    "MGM": "Consumer Discretionary",
    "MKC": "Consumer Staples",
    "MLM": "Materials",
    "MMM": "Industrials",
    "MNST": "Consumer Staples",
    "MO": "Consumer Staples",
    "MOS": "Materials",
    "MP": "Materials",
    "MPC": "Energy",
    "MPWR": "Information Technology",
    "MRK": "Health Care",
    "MRNA": "Health Care",
    "MRSH": "Financials",
    "MS": "Financials",
    "MSCI": "Financials",
    "MSFT": "Information Technology",
    "MSI": "Information Technology",
    "MTB": "Financials",
    "MTD": "Health Care",
    "MU": "Information Technology",
    "MUX": "Materials",
    "MWA": "Industrials",
    "NAK": "Materials",
    "NCLH": "Consumer Discretionary",
    "NDAQ": "Financials",
    "NDSN": "Industrials",
    "NEE": "Utilities",
    "NEM": "Materials",
    "NFLX": "Communication Services",
    "NG": "Materials",
    "NI": "Utilities",
    "NKE": "Consumer Discretionary",
    "NOC": "Industrials",
    "NOW": "Information Technology",
    "NRG": "Utilities",
    "NSC": "Industrials",
    "NTAP": "Information Technology",
    "NTRS": "Financials",
    "NUE": "Materials",
    "NVDA": "Information Technology",
    "NVR": "Consumer Discretionary",
    "NWS": "Communication Services",
    "NWSA": "Communication Services",
    "NXPI": "Information Technology",
    "O": "Real Estate",
    "ODFL": "Industrials",
    "OKE": "Energy",
    "OKLO": "Utilities",
    "OMC": "Communication Services",
    "OMCL": "Health Care",
    "ON": "Information Technology",
    "ONDS": "Information Technology",
    "ORCL": "Information Technology",
    "ORLY": "Consumer Discretionary",
    "OTIS": "Industrials",
    "OTLY": "Consumer Staples",
    "OUST": "Information Technology",
    "OXY": "Energy",
    "PANW": "Information Technology",
    "PATH": "Information Technology",
    "PAYX": "Industrials",
    "PCAR": "Industrials",
    "PCG": "Utilities",
    "PEG": "Utilities",
    "PEP": "Consumer Staples",
    "PFE": "Health Care",
    "PFG": "Financials",
    "PG": "Consumer Staples",
    "PGR": "Financials",
    "PH": "Industrials",
    "PHM": "Consumer Discretionary",
    "PKG": "Materials",
    "PLD": "Real Estate",
    "PLTR": "Information Technology",
    "PM": "Consumer Staples",
    "PNC": "Financials",
    "PNR": "Industrials",
    "PNW": "Utilities",
    "PODD": "Health Care",
    "POOL": "Consumer Discretionary",
    "PPG": "Materials",
    "PPL": "Utilities",
    "PRU": "Financials",
    "PSA": "Real Estate",
    "PSKY": "Communication Services",
    "PSX": "Energy",
    "PTC": "Information Technology",
    "PVLA": "Health Care",
    "PWR": "Industrials",
    "PYPL": "Financials",
    "Q": "Information Technology",
    "QBTS": "Information Technology",
    "QCOM": "Information Technology",
    "QFIN": "Financials",
    "QLYS": "Information Technology",
    "QS": "Industrials",
    "QUBT": "Information Technology",
    "RCL": "Consumer Discretionary",
    "RDW": "Industrials",
    "RDWR": "Information Technology",
    "REG": "Real Estate",
    "REGN": "Health Care",
    "RF": "Financials",
    "RGTI": "Information Technology",
    "RJF": "Financials",
    "RKLB": "Industrials",
    "RL": "Consumer Discretionary",
    "RMD": "Health Care",
    "ROK": "Industrials",
    "ROL": "Industrials",
    "ROP": "Information Technology",
    "ROST": "Consumer Discretionary",
    "RPAY": "Financials",
    "RR": "Industrials",
    "RSG": "Industrials",
    "RTX": "Industrials",
    "RUN": "Utilities",
    "RVTY": "Health Care",
    "S": "Information Technology",
    "SATS": "Communication Services",
    "SBAC": "Real Estate",
    "SBUX": "Consumer Discretionary",
    "SCHW": "Financials",
    "SCWX": "Information Technology",
    "SERV": "Industrials",
    "SEZL": "Financials",
    "SGMO": "Health Care",
    "SHW": "Materials",
    "SIDU": "Industrials",
    "SJM": "Consumer Staples",
    "SLB": "Energy",
    "SLDP": "Industrials",
    "SMCI": "Information Technology",
    "SNA": "Industrials",
    "SNDK": "Information Technology",
    "SNPS": "Information Technology",
    "SO": "Utilities",
    "SOFI": "Financials",
    "SOLV": "Health Care",
    "SOUN": "Information Technology",
    "SPG": "Real Estate",
    "SPGI": "Financials",
    "SRE": "Utilities",
    "STE": "Health Care",
    "STEM": "Industrials",
    "STLD": "Materials",
    "STT": "Financials",
    "STX": "Information Technology",
    "STZ": "Consumer Staples",
    "SW": "Materials",
    "SWK": "Industrials",
    "SWKS": "Information Technology",
    "SYF": "Financials",
    "SYK": "Health Care",
    "SYY": "Consumer Staples",
    "T": "Communication Services",
    "TAP": "Consumer Staples",
    "TDC": "Information Technology",
    "TDG": "Industrials",
    "TDY": "Information Technology",
    "TECH": "Health Care",
    "TEL": "Information Technology",
    "TER": "Information Technology",
    "TERN": "Health Care",
    "TFC": "Financials",
    "TGT": "Consumer Staples",
    "TJX": "Consumer Discretionary",
    "TKO": "Communication Services",
    "TMC": "Materials",
    "TMO": "Health Care",
    "TMUS": "Communication Services",
    "TPL": "Energy",
    "TPR": "Consumer Discretionary",
    "TRGP": "Energy",
    "TRMB": "Information Technology",
    "TROW": "Financials",
    "TRV": "Financials",
    "TSCO": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",
    "TSN": "Consumer Staples",
    "TT": "Industrials",
    "TTD": "Communication Services",
    "TTWO": "Communication Services",
    "TXN": "Information Technology",
    "TXT": "Industrials",
    "TYL": "Information Technology",
    "UAL": "Industrials",
    "UBER": "Industrials",
    "UDR": "Real Estate",
    "UHS": "Health Care",
    "ULTA": "Consumer Discretionary",
    "UNH": "Health Care",
    "UNP": "Industrials",
    "UPS": "Industrials",
    "URI": "Industrials",
    "USAR": "Materials",
    "USB": "Financials",
    "V": "Financials",
    "VEEV": "Health Care",
    "VICI": "Real Estate",
    "VKTX": "Health Care",
    "VLO": "Energy",
    "VLTO": "Industrials",
    "VMC": "Materials",
    "VRNS": "Information Technology",
    "VRSK": "Industrials",
    "VRSN": "Information Technology",
    "VRT": "Industrials",
    "VRTX": "Health Care",
    "VST": "Utilities",
    "VTR": "Real Estate",
    "VTRS": "Health Care",
    "VZ": "Communication Services",
    "WAB": "Industrials",
    "WAT": "Health Care",
    "WBD": "Communication Services",
    "WDAY": "Information Technology",
    "WDC": "Information Technology",
    "WEC": "Utilities",
    "WELL": "Real Estate",
    "WFC": "Financials",
    "WM": "Industrials",
    "WMB": "Energy",
    "WMT": "Consumer Staples",
    "WRB": "Financials",
    "WSM": "Consumer Discretionary",
    "WST": "Health Care",
    "WTTR": "Energy",
    "WTW": "Financials",
    "WY": "Real Estate",
    "WYNN": "Consumer Discretionary",
    "XEL": "Utilities",
    "XOM": "Energy",
    "XYL": "Industrials",
    "XYZ": "Financials",
    "YUM": "Consumer Discretionary",
    "ZBH": "Health Care",
    "ZBRA": "Information Technology",
    "ZS": "Information Technology",
    "ZTS": "Health Care",
}

# S&P MidCap 400: clasificacion GICS oficial publicada junto con la composicion
# del indice (Wikipedia, misma tabla de la que salio _SP400_TICKERS en
# screener_config.py, 2026-07-29). Provenance distinta -- y mas fuerte -- que la
# del mapeo de arriba: es la clasificacion del proveedor del indice, no una
# verificacion de terceros ticker por ticker. Los 11 valores distintos se
# chequearon contra SECTOR_ETF (cero sin reconocer) y los 5 tickers que solapan
# con el mapeo curado a mano coinciden exactamente, lo que valida de forma
# cruzada ambas fuentes.
#
# Por que importa que esto exista: sin sector, get_sector() devuelve None y eso
# NO es neutro para el backtest de la estrategia Oportunista -- desactiva
# sector_exit por completo (backtest.py: sector_etf_close=None -> el chequeo
# jamas corre) y clava el componente sector_relative_strength del score en 0.0
# (11.5% del peso), o sea "rindio igual que su sector", que en regimenes malos
# le gana artificialmente a los simbolos con lectura real negativa. Cuando estos
# 395 tickers se agregaron al universo sin su sector, el backtest mostro el
# drawdown casi duplicado (-27.8% -> -43.2%) por esta razon mecanica, no por
# una inferioridad real de las midcaps.
_SP400_GICS_SECTOR: dict[str, str] = {
    "AA": "Materials",
    "AAL": "Industrials",
    "AAON": "Industrials",
    "ACI": "Consumer Staples",
    "ACM": "Industrials",
    "ADC": "Real Estate",
    "AEIS": "Information Technology",
    "AFG": "Financials",
    "AGCO": "Industrials",
    "AHR": "Real Estate",
    "AIT": "Industrials",
    "ALGM": "Information Technology",
    "ALK": "Industrials",
    "ALLY": "Financials",
    "ALSN": "Industrials",
    "ALV": "Consumer Discretionary",
    "AM": "Energy",
    "AMG": "Financials",
    "AMH": "Real Estate",
    "AMKR": "Information Technology",
    "AN": "Consumer Discretionary",
    "ANF": "Consumer Discretionary",
    "APG": "Industrials",
    "APPF": "Information Technology",
    "AR": "Energy",
    "ARMK": "Consumer Discretionary",
    "ARW": "Information Technology",
    "ARWR": "Health Care",
    "ASB": "Financials",
    "ASH": "Materials",
    "ATI": "Industrials",
    "ATR": "Materials",
    "AVNT": "Materials",
    "AVT": "Information Technology",
    "AVTR": "Health Care",
    "AXTA": "Materials",
    "AYI": "Industrials",
    "BAH": "Industrials",
    "BBWI": "Consumer Discretionary",
    "BC": "Consumer Discretionary",
    "BCO": "Industrials",
    "BDC": "Information Technology",
    "BHF": "Financials",
    "BILL": "Information Technology",
    "BIO": "Health Care",
    "BJ": "Consumer Staples",
    "BKH": "Utilities",
    "BMRN": "Health Care",
    "BRKR": "Health Care",
    "BROS": "Consumer Discretionary",
    "BRX": "Real Estate",
    "BSY": "Information Technology",
    "BTSG": "Health Care",
    "BURL": "Consumer Discretionary",
    "BWA": "Consumer Discretionary",
    "BWXT": "Industrials",
    "BYD": "Consumer Discretionary",
    "CACI": "Industrials",
    "CAR": "Industrials",
    "CART": "Consumer Staples",
    "CAVA": "Consumer Discretionary",
    "CBSH": "Financials",
    "CBT": "Materials",
    "CCK": "Materials",
    "CDE": "Materials",
    "CDP": "Real Estate",
    "CELH": "Consumer Staples",
    "CFR": "Financials",
    "CG": "Financials",
    "CGNX": "Information Technology",
    "CHDN": "Consumer Discretionary",
    "CHE": "Health Care",
    "CHH": "Consumer Discretionary",
    "CHRD": "Energy",
    "CHWY": "Consumer Discretionary",
    "CLF": "Materials",
    "CLH": "Industrials",
    "CMC": "Materials",
    "CNH": "Industrials",
    "CNM": "Industrials",
    "CNO": "Financials",
    "CNX": "Energy",
    "COKE": "Consumer Staples",
    "COLB": "Financials",
    "COLM": "Consumer Discretionary",
    "CPRI": "Consumer Discretionary",
    "CR": "Industrials",
    "CRBG": "Financials",
    "CROX": "Consumer Discretionary",
    "CRS": "Industrials",
    "CRUS": "Information Technology",
    "CSL": "Industrials",
    "CTRE": "Real Estate",
    "CUBE": "Real Estate",
    "CUZ": "Real Estate",
    "CVLT": "Information Technology",
    "CW": "Industrials",
    "CXT": "Information Technology",
    "CYTK": "Health Care",
    "DAR": "Consumer Staples",
    "DBX": "Information Technology",
    "DCI": "Industrials",
    "DINO": "Energy",
    "DKS": "Consumer Discretionary",
    "DLB": "Information Technology",
    "DOCN": "Information Technology",
    "DOCS": "Health Care",
    "DOCU": "Information Technology",
    "DT": "Information Technology",
    "DTM": "Energy",
    "DUOL": "Consumer Discretionary",
    "DY": "Industrials",
    "EEFT": "Financials",
    "EGP": "Real Estate",
    "EHC": "Health Care",
    "ELAN": "Health Care",
    "ELF": "Consumer Staples",
    "ELS": "Real Estate",
    "ENS": "Industrials",
    "ENSG": "Health Care",
    "ENTG": "Information Technology",
    "EPR": "Real Estate",
    "EQH": "Financials",
    "ESAB": "Industrials",
    "ESNT": "Financials",
    "EVR": "Financials",
    "EWBC": "Financials",
    "EXEL": "Health Care",
    "EXLS": "Industrials",
    "EXP": "Materials",
    "EXPO": "Industrials",
    "FAF": "Financials",
    "FBIN": "Industrials",
    "FCFS": "Financials",
    "FCN": "Industrials",
    "FFIN": "Financials",
    "FHI": "Financials",
    "FHN": "Financials",
    "FIVE": "Consumer Discretionary",
    "FLG": "Financials",
    "FLR": "Industrials",
    "FLS": "Industrials",
    "FN": "Information Technology",
    "FNB": "Financials",
    "FND": "Consumer Discretionary",
    "FNF": "Financials",
    "FOUR": "Financials",
    "FR": "Real Estate",
    "FTI": "Energy",
    "G": "Industrials",
    "GAP": "Consumer Discretionary",
    "GATX": "Industrials",
    "GBCI": "Financials",
    "GEF": "Materials",
    "GGG": "Industrials",
    "GHC": "Consumer Discretionary",
    "GLPI": "Real Estate",
    "GME": "Consumer Discretionary",
    "GMED": "Health Care",
    "GNTX": "Consumer Discretionary",
    "GPK": "Materials",
    "GWRE": "Information Technology",
    "GXO": "Industrials",
    "H": "Consumer Discretionary",
    "HAE": "Health Care",
    "HALO": "Health Care",
    "HGV": "Consumer Discretionary",
    "HIMS": "Health Care",
    "HL": "Materials",
    "HLI": "Financials",
    "HLNE": "Financials",
    "HOG": "Consumer Discretionary",
    "HOMB": "Financials",
    "HQY": "Health Care",
    "HR": "Real Estate",
    "HRB": "Consumer Discretionary",
    "HWC": "Financials",
    "HXL": "Industrials",
    "IBOC": "Financials",
    "IDA": "Utilities",
    "IDCC": "Information Technology",
    "IESC": "Industrials",
    "ILMN": "Health Care",
    "INGR": "Consumer Staples",
    "IPGP": "Information Technology",
    "IRT": "Real Estate",
    "ITT": "Industrials",
    "JAZZ": "Health Care",
    "JEF": "Financials",
    "JLL": "Real Estate",
    "KBH": "Consumer Discretionary",
    "KBR": "Industrials",
    "KD": "Information Technology",
    "KEX": "Industrials",
    "KNF": "Materials",
    "KNSL": "Financials",
    "KNX": "Industrials",
    "KRC": "Real Estate",
    "KRG": "Real Estate",
    "KRYS": "Health Care",
    "LAD": "Consumer Discretionary",
    "LAMR": "Real Estate",
    "LEA": "Consumer Discretionary",
    "LECO": "Industrials",
    "LFUS": "Information Technology",
    "LIVN": "Health Care",
    "LNTH": "Health Care",
    "LOPE": "Consumer Discretionary",
    "LPX": "Industrials",
    "LSCC": "Information Technology",
    "LSTR": "Industrials",
    "M": "Consumer Discretionary",
    "MANH": "Information Technology",
    "MAT": "Consumer Discretionary",
    "MEDP": "Health Care",
    "MIDD": "Industrials",
    "MKSI": "Information Technology",
    "MLI": "Industrials",
    "MMS": "Industrials",
    "MOG-A": "Industrials",
    "MOH": "Health Care",
    "MORN": "Financials",
    "MSA": "Industrials",
    "MSM": "Industrials",
    "MTDR": "Energy",
    "MTG": "Financials",
    "MTN": "Consumer Discretionary",
    "MTSI": "Information Technology",
    "MTZ": "Industrials",
    "MUR": "Energy",
    "MUSA": "Consumer Discretionary",
    "MZTI": "Consumer Staples",
    "NBIX": "Health Care",
    "NEU": "Materials",
    "NFG": "Utilities",
    "NJR": "Utilities",
    "NLY": "Financials",
    "NNN": "Real Estate",
    "NOV": "Energy",
    "NOVT": "Information Technology",
    "NTNX": "Information Technology",
    "NVST": "Health Care",
    "NVT": "Industrials",
    "NWE": "Utilities",
    "NXST": "Communication Services",
    "NXT": "Industrials",
    "NYT": "Communication Services",
    "OC": "Industrials",
    "OGE": "Utilities",
    "OGS": "Utilities",
    "OHI": "Real Estate",
    "OKTA": "Information Technology",
    "OLED": "Information Technology",
    "OLLI": "Consumer Discretionary",
    "OLN": "Materials",
    "ONB": "Financials",
    "ONTO": "Information Technology",
    "OPCH": "Health Care",
    "ORA": "Utilities",
    "ORI": "Financials",
    "OSK": "Industrials",
    "OVV": "Energy",
    "OZK": "Financials",
    "P": "Information Technology",
    "PAG": "Consumer Discretionary",
    "PB": "Financials",
    "PBF": "Energy",
    "PCTY": "Industrials",
    "PEGA": "Information Technology",
    "PEN": "Health Care",
    "PFGC": "Consumer Staples",
    "PII": "Consumer Discretionary",
    "PINS": "Communication Services",
    "PK": "Real Estate",
    "PLNT": "Consumer Discretionary",
    "PNFP": "Financials",
    "POR": "Utilities",
    "POST": "Consumer Staples",
    "PPC": "Consumer Staples",
    "PR": "Energy",
    "PRI": "Financials",
    "PSN": "Industrials",
    "PVH": "Consumer Discretionary",
    "R": "Industrials",
    "RBA": "Industrials",
    "RBC": "Industrials",
    "REXR": "Real Estate",
    "RGA": "Financials",
    "RGEN": "Health Care",
    "RGLD": "Materials",
    "RH": "Consumer Discretionary",
    "RLI": "Financials",
    "RMBS": "Information Technology",
    "RNR": "Financials",
    "ROIV": "Health Care",
    "ROKU": "Communication Services",
    "RPM": "Materials",
    "RRC": "Energy",
    "RRX": "Industrials",
    "RS": "Materials",
    "RYAN": "Financials",
    "RYN": "Real Estate",
    "SAIA": "Industrials",
    "SAIC": "Industrials",
    "SAM": "Consumer Staples",
    "SANM": "Information Technology",
    "SARO": "Industrials",
    "SBRA": "Real Estate",
    "SCI": "Consumer Discretionary",
    "SEIC": "Financials",
    "SF": "Financials",
    "SFM": "Consumer Staples",
    "SGI": "Consumer Discretionary",
    "SHC": "Health Care",
    "SIGI": "Financials",
    "SIRI": "Communication Services",
    "SITM": "Information Technology",
    "SLAB": "Information Technology",
    "SLGN": "Materials",
    "SLM": "Financials",
    "SMG": "Materials",
    "SMTC": "Information Technology",
    "SN": "Consumer Discretionary",
    "SNX": "Information Technology",
    "SOLS": "Materials",
    "SON": "Materials",
    "SPXC": "Industrials",
    "SR": "Utilities",
    "SSB": "Financials",
    "SSD": "Industrials",
    "ST": "Industrials",
    "STAG": "Real Estate",
    "STRL": "Industrials",
    "STWD": "Financials",
    "SWX": "Utilities",
    "SYNA": "Information Technology",
    "TCBI": "Financials",
    "TEX": "Industrials",
    "THC": "Health Care",
    "THG": "Financials",
    "THO": "Consumer Discretionary",
    "TKR": "Industrials",
    "TLN": "Utilities",
    "TNL": "Consumer Discretionary",
    "TOL": "Consumer Discretionary",
    "TOST": "Financials",
    "TREX": "Industrials",
    "TRU": "Industrials",
    "TTC": "Industrials",
    "TTEK": "Industrials",
    "TTMI": "Information Technology",
    "TWLO": "Information Technology",
    "TXNM": "Utilities",
    "TXRH": "Consumer Discretionary",
    "UBSI": "Financials",
    "UFPI": "Industrials",
    "UGI": "Utilities",
    "ULS": "Industrials",
    "UMBF": "Financials",
    "UNM": "Financials",
    "USFD": "Consumer Staples",
    "UTHR": "Health Care",
    "VAL": "Energy",
    "VC": "Consumer Discretionary",
    "VFC": "Consumer Discretionary",
    "VIAV": "Information Technology",
    "VICR": "Industrials",
    "VLY": "Financials",
    "VMI": "Industrials",
    "VNO": "Real Estate",
    "VNOM": "Energy",
    "VNT": "Information Technology",
    "VOYA": "Financials",
    "VVV": "Consumer Discretionary",
    "WAL": "Financials",
    "WBS": "Financials",
    "WCC": "Industrials",
    "WEX": "Financials",
    "WFRD": "Energy",
    "WH": "Consumer Discretionary",
    "WHR": "Consumer Discretionary",
    "WING": "Consumer Discretionary",
    "WLK": "Materials",
    "WMG": "Communication Services",
    "WMS": "Industrials",
    "WPC": "Real Estate",
    "WSO": "Industrials",
    "WTFC": "Financials",
    "WTRG": "Utilities",
    "WTS": "Industrials",
    "WWD": "Industrials",
    "XPO": "Industrials",
    "XRAY": "Health Care",
    "YETI": "Consumer Discretionary",
    "ZION": "Financials",
}

# Un solo mapeo consultable para get_sector()/RulesEngine: el de arriba curado a
# mano mas la clasificacion oficial del S&P 400.
TICKER_SECTOR.update(_SP400_GICS_SECTOR)


_VALID_SECTORS = frozenset({
    "Information Technology",
    "Health Care",
    "Financials",
    "Consumer Discretionary",
    "Consumer Staples",
    "Communication Services",
    "Industrials",
    "Energy",
    "Utilities",
    "Real Estate",
    "Materials",
})

# ETF sectorial SPDR de cada sector GICS: permite medir la fuerza relativa de
# un simbolo contra su propio sector (en vez de solo contra el benchmark
# general, ej. SPY), reusando get_daily_bars (ya cacheado) en lugar de pedir
# una canasta de pares por simbolo.
SECTOR_ETF: dict[str, str] = {
    "Information Technology": "XLK",
    "Health Care": "XLV",
    "Financials": "XLF",
    "Consumer Discretionary": "XLY",
    "Consumer Staples": "XLP",
    "Communication Services": "XLC",
    "Industrials": "XLI",
    "Energy": "XLE",
    "Utilities": "XLU",
    "Real Estate": "XLRE",
    "Materials": "XLB",
}


def get_sector(symbol: str) -> Optional[str]:
    """Sector GICS de `symbol`, o None si no esta clasificado todavia.

    No golpea la red: ademas del mapeo estatico (curado a mano), consulta
    `_runtime_sector_cache`, poblado unicamente por `refresh_sector()`/el
    endpoint "refrescar sectores" del dashboard. Esto preserva la garantia de
    RulesEngine.evaluate() (sincrono, sin red) sin perder la clasificacion de
    un ticker nuevo una vez que alguien la pidio explicitamente."""
    key = symbol.upper()
    sector = TICKER_SECTOR.get(key)
    if sector is not None:
        return sector
    return _runtime_sector_cache.get(key)


# Yahoo Finance (yfinance .info["sector"]) usa su propia taxonomia (Morningstar),
# distinta en nombres de los 11 sectores GICS estandar que usa el resto del
# codigo (_VALID_SECTORS). Se traduce aca para que un ticker resuelto en vivo
# sea indistinguible, para RulesEngine y el frontend, de uno del mapeo estatico.
_YFINANCE_SECTOR_MAP: dict[str, str] = {
    "Technology": "Information Technology",
    "Healthcare": "Health Care",
    "Financial Services": "Financials",
    "Consumer Cyclical": "Consumer Discretionary",
    "Consumer Defensive": "Consumer Staples",
    "Industrials": "Industrials",
    "Energy": "Energy",
    "Utilities": "Utilities",
    "Real Estate": "Real Estate",
    "Basic Materials": "Materials",
    "Communication Services": "Communication Services",
}

# Cache de tickers resueltos en vivo (ver refresh_sector). Separado de
# TICKER_SECTOR (el mapeo curado a mano) para no mezclar datos verificados con
# datos de mejor esfuerzo provenientes de una API de terceros sin garantias.
_runtime_sector_cache: dict[str, Optional[str]] = {}


def refresh_sector(symbol: str) -> Optional[str]:
    """Resuelve el sector de `symbol` contra Yahoo Finance y lo cachea en
    `_runtime_sector_cache` para que `get_sector()` lo siga devolviendo sin
    red. Pensado para tickers nuevos que el usuario agrega al universo desde
    el dashboard y que todavia no estan en el mapeo estatico TICKER_SECTOR.

    Llamada explicita y fuera del camino caliente de RulesEngine (ver
    docstring de get_sector): quien la invoca (el endpoint
    POST /api/sectors/refresh) es responsable de no llamarla desde codigo
    sincrono que deba permanecer libre de red."""
    key = symbol.upper()
    try:
        info = _fetch_with_timeout(lambda: yf.Ticker(symbol).get_info()) or {}
    except Exception:
        info = {}
    raw_sector = info.get("sector")
    sector = _YFINANCE_SECTOR_MAP.get(raw_sector) if raw_sector else None
    _runtime_sector_cache[key] = sector
    return sector
